chat-gpt:
  api-key: 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


spring:
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false